version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
    ports:
      - 3000:80
    depends_on:
      - product-catalog
      - store-catalog
      - shopping-cart
  product-catalog:
    build:
      context: ../product-catalog
      dockerfile: Dockerfile.dev
    environment:
      - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://db:5432/central
    ports:
      - 8080:8080
    depends_on:
      - db
  store-catalog:
    build:
      context: ../store-catalog
      dockerfile: Dockerfile.dev
    environment:
      - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://db:5432/central
    ports:
      - 8081:8080
    depends_on:
      - db
  shopping-cart:
    build:
      context: ../shopping-cart
      dockerfile: Dockerfile.dev
    environment:
      - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://db:5432/central
    ports:
      - 8082:8080
    depends_on:
      - db
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 7000:8080
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=central
    ports:
      - 5432:5432

